title: Cesare Straffelini
logo: /assets/img/223287416.jpg
show_downloads: false
description: ""
google_analytics:
theme: jekyll-theme-minimal

# Biographic information
avatar           : "profile.png"
name             : "Cesare Straffelini"
pronouns         : "he/him"  
bio              : "PhD student in Trento & Barcelona"
location         : "Gran Via de les Corts Catalanes 585 <br>08007 Barcelona"
employer         : "Universitat de Barcelona"
uri              : # URL
email            : "straffelini@ub.edu" 

# Academic websites
arxiv            : "https://arxiv.org/search/math?searchtype=author&query=Straffelini,+C"
googlescholar    : # "https://scholar.google.com/citations?user=jEFOH84AAAAJ&hl=en"
researchgate     : # "https://www.researchgate.net/profile/Umberto-Tarantino-3"
scopus           : # URL
  

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
