title: Umberto Tarantino
logo: /assets/img/logo.png
description: PhD student in Theoretical Computer Science @ IRIF, Université Paris Cité
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
